system_settings:
  # Limit on host RAM use in Gb (0 for no configuration limit)
  max_host_ram : 0
  # Limit on GPU RAM use in Gb ( 0 for no configuration limit)
  max_gpu_ram  : 0

input_settings:
  # Folder to write the code input configuration files
  input_folder : "."
  # Name of the scatterer description file
  spheres_file : "DEDFB"
  # Name of the geometry description file
  geometry_file: "DSPH"
  
output_settings:
  # Index of the scale for transition matrix output
  jwtm         : 1

particle_settings:
  # What application to use (SPHERE | CLUSTER | INCLUSION)
  application : "SPHERE"
  # Number of spheres
  n_spheres   : 1
  # Number of sphere types
  n_types     : 1
  # Vector of sphere type identifiers (what type is each sphere)
  sph_types   : [ 1 ]
  # Vector of layers in types (how many layers in each type)
  n_layers    : [ 2 ]
  # Spherical monomer radii in m (one size for each type)
  radii       : [ 4.0e-8 ]
  # Layer fractional radii (one per layer in each type)
  rad_frac    : [ [ 0.75, 1.0 ] ]
  # Index of the dielectric functions (one per layer in each type)
  #
  # 1 is first file in `dielec_file`, 2 is second ...
  dielec_id   : [ ]

material_settings:
  diel_flag   : -1
  # External medium dielectric constant
  extern_diel : 1.7689e+00
  # Dielectric function files folder
  dielec_path : "."
  # List of dielectric function files (used if diel_flag = 0)
  dielec_file : [ ]
  # Dielectric function files format (same for all files)
  dielec_fmt  : [ "CSV" ]
  # Matching method between optical functions and radiation wavelengths
  #
  # INTERPOLATE: the functions are interpolated on wavelengths
  # GRID: only the wavelengths with defined functions are computed
  #
  match_mode  : "GRID"
  # Reference dielectric functions (used if diel_flag = -1)
  #
  # One real and one imaginary part for each layer in each type.
  diel_func   : [
    [ 2.25e00, 2.56e-03, 2.25e00, 2.56e-03 ]
    ]

radiation_settings:
  # Radiation field polarization (LINEAR | CIRCULAR)
  polarization: "LINEAR"
  # First scale to be used
  scale_start : 1.0e+00
  # Last scale to be used
  scale_end   : 2.0e+00
  # Calculation step (overridden if `match_mode` is GRID)
  scale_step  : 1.0e+00
  # Peak Omega
  wp          : 1.7715748e+15
  # Peak scale
  xip         : 1.0e+00
  # Define scale explicitly (0) or in equal steps (1)
  step_flag   : 0
  # Type of scaling variable
  scale_name  : "XI"

geometry_settings:
  # Maximum internal field expansion
  li          : 8
  # Maximum external field expansion (not used by SPHERE)
  le          : 8
  # Number of transition layer integration points
  npnt        : 149
  # Number of non transition layer integration points
  npntts      : 300
  # Meridional plane flag
  isam        : 0
  # Starting incidence azimuth angle
  in_th_start : 79.0
  # Incidence azimuth angle incremental step
  in_th_step  : 10.0
  # Ending incidence azimuth angle
  in_th_end   : 89.0
  # Starting incidence elevation angle
  in_ph_start : 0.0
  # Incidence elevation angle incremental step
  in_ph_step  : 10.0
  # Ending incidence elevation angle
  in_ph_end   : 10.0
  # Starting scattered azimuth angle
  sc_th_start : 34.0
  # Scattered azimuth angle incremental step
  sc_th_step  : 15.0
  # Ending scattered azimuth angle
  sc_th_end   : 49.0
  # Starting scattered elevation angle
  sc_ph_start : 5.0
  # Scattered elevation angle incremental step
  sc_ph_step  : 5.0
  # Ending scattered elevation angle
  sc_ph_end   : 10.0
  # Vector of sphere X coordinates (one per sphere or empty for random)
  x_coords    : [ ]
  # Vector of sphere Y coordinates (one per sphere or empty for random)
  y_coords    : [ ]
  # Vector of sphere Z coordinates (one per sphere or empty for random)
  z_coords    : [ ]
